on: [push] #change

jobs:
  push_to_confluence:
    runs-on: ubuntu-latest
    name: Converting Markdown to Confluence
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Conversion step
        uses: TTengs/MarkdownToConfluence@v0.3 # Uses an action in the root directory
        id: convert
        with:
          fileslocation: './testdocs'